/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIdRouteImport } from './routes/study.$id'
import { Route as CoursesCodeRouteImport } from './routes/courses.$code'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdRoute = StudyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudyRoute,
} as any)
const CoursesCodeRoute = CoursesCodeRouteImport.update({
  id: '/courses/$code',
  path: '/courses/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRouteWithChildren
  '/courses/$code': typeof CoursesCodeRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRouteWithChildren
  '/courses/$code': typeof CoursesCodeRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRouteWithChildren
  '/courses/$code': typeof CoursesCodeRoute
  '/study/$id': typeof StudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/search'
    | '/study'
    | '/courses/$code'
    | '/study/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/search'
    | '/study'
    | '/courses/$code'
    | '/study/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/search'
    | '/study'
    | '/courses/$code'
    | '/study/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  SearchRoute: typeof SearchRoute
  StudyRoute: typeof StudyRouteWithChildren
  CoursesCodeRoute: typeof CoursesCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id': {
      id: '/study/$id'
      path: '/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof StudyIdRouteImport
      parentRoute: typeof StudyRoute
    }
    '/courses/$code': {
      id: '/courses/$code'
      path: '/courses/$code'
      fullPath: '/courses/$code'
      preLoaderRoute: typeof CoursesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudyRouteChildren {
  StudyIdRoute: typeof StudyIdRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyIdRoute: StudyIdRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  SearchRoute: SearchRoute,
  StudyRoute: StudyRouteWithChildren,
  CoursesCodeRoute: CoursesCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
